version: "3.7"
services:
  api:
    build: "./zv-api"
    ports: 
      - "3000:3000"
    depends_on: 
      - mongo
  mongo:
    image: "mongo:4.1.6"
    restart: "always"
    ports:
      - "27017:27017"

